[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[runner]
magicEnabled = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#FF6B35"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFFFFF"
font = "sans serif"
